FROM alpine:edge AS downloader
RUN apk add go git curl gzip && apk upgrade
WORKDIR /geodata
RUN git clone --single-branch --branch release --depth 1 https://github.com/MetaCubeX/meta-rules-dat meta_rules && \
    cd meta_rules && \
    sha256sum -c GeoLite2-ASN.mmdb.sha256sum && \
    sha256sum -c geoip.dat.sha256sum && \
    sha256sum -c geosite.dat.sha256sum && \
    mv GeoLite2-ASN.mmdb /geodata/ASN.mmdb && \
    mv geoip.dat /geodata/GeoIP.dat && \
    mv geosite.dat /geodata/GeoSite.dat && \
    cd .. && \
    rm -rf meta_rules && \
    geodate=$(curl -s https://github.com/MetaCubeX/meta-rules-dat/commits/release.atom | sed -n 's/.*<updated>\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}T[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}Z\)<\/updated>.*/\1/p' | head -1) && \
    printf 'ASN.mmdb,%s\nGeoSite.dat,%s\nGeoIP.dat,%s\n' "$geodate" "$geodate" "$geodate" > /geodata/update.log && \
    cat /geodata/update.log
RUN ver=$(curl -s https://github.com/MetaCubeX/mihomo/releases | \
    grep mihomo-android- | \
    grep MetaCubeX/mihomo/releases | \
    grep -Eo "download/[^/]+" | \
    cut -d"/" -f2 | \
    head -1) && \
    echo "Version: $ver" && \
    downlink_arm64="https://github.com/MetaCubeX/mihomo/releases/download/${ver}/mihomo-linux-arm64-${ver}.gz" && \
    curl -L "$downlink_arm64" -o /tmp/mihomo_arm64.gz && \
    gunzip /tmp/mihomo_arm64.gz && \
    ls -lah /tmp/ && \
    mv /tmp/mihomo_arm64 /usr/bin/mihomo_arm64 && \
    chmod +x /usr/bin/mihomo_arm64 && \
    od -An -tx1 -j0 -N4 /usr/bin/mihomo_arm64 | grep -q "7f 45 4c 46" && \
    od -An -tx1 -j18 -N2 /usr/bin/mihomo_arm64 | grep -q "b7 00" && \
    [ "$(stat -c %s /usr/bin/mihomo_arm64)" -gt 1000000 ] && \
    echo "mihomo aarch64 ELF OK" && \
    rm -rf /tmp/*
FROM alpine:edge
RUN apk add --no-cache xorriso 7zip
COPY --from=downloader /usr/bin/mihomo_arm64 /clash/
COPY --from=downloader /geodata/ASN.mmdb /geodata/ASN.mmdb
COPY --from=downloader /geodata/GeoSite.dat /geodata/GeoSite.dat
COPY --from=downloader /geodata/GeoIP.dat /geodata/GeoIP.dat
COPY --from=downloader /geodata/update.log /geodata/update.log
WORKDIR /data
COPY ./remakeiso.sh /
COPY ./root.7z /
RUN chmod +x /remakeiso.sh
ENV sha="rootsha"
ENV SNIFF=yes
ENV GEO=yes
ENV MI=y
ENTRYPOINT ["/remakeiso.sh"]
