// Copyright (c) 2026, https://blog.03k.org. All rights reserved.

pub mod acl;
pub mod auth;
pub mod clash_ctl;
pub mod clash_logs;
pub mod connections;
pub mod events;
pub mod geo;
pub mod http;
mod idle_gate;
pub mod info;
pub mod native;
pub mod nodes;
pub mod probe;
pub mod proxies;
pub mod proxy_unix;
pub mod respond;
pub mod router;
pub mod screen;
mod screen_poll;
pub mod server;
pub mod sse;
pub mod static_files;
pub mod traffic;
pub mod ws;

pub use acl::{AdminAcl, AdminHandle, admin_handle};
pub use auth::{TokenHandle, check_bearer, derive_secret, token_handle};
pub use clash_ctl::ClashControl;
pub use connections::ConnectionsSource;
pub use events::{LogEvent, LogSource, LogTx};
pub use geo::GeoControl;
pub use info::{InfoScope, InfoSource};
pub use nodes::NodesSource;
pub use probe::{Busy, ProbeSource};
pub use proxies::ProxiesSource;
pub use screen::ScreenHistory;
pub use server::{ServerConfig, run, serve};
pub use traffic::TrafficSource;
